travis:
  secure:
    BINSTAR_TOKEN: VShAJJhSbE0mhZTuSdecBJLUtPRCgrz40PomB2HenDdZ0VutOAf8Tn+Sv3UY31S+invgqB3o+DkdMHg8Klj7HP5GOLNoIoVhihC2aKUBaj/7jl0AZNCK6jx5vm2UClGL9QKnR7xo2RiDLZaunnrRPtBt9m/1LMBEkV6g8Smx0fcWJyz/ALWnjtGdh6xknFHM0I8INsQHUM1k8m9VJas/pRifBRzTil5I1sIL36GkWZRk4qq9oilyTEz7iFCMt9sytOkOXoGsX8VFzOiJbNUqZZd9v4yL18fD3stBmV8LGNBYbD+EFdVFTmLbpFy7JLbGJN4lqUnB3XsyfSyxMQCL0hyrqdmSf76Zg2qVZnlaL5FP7EGdsy1NZzfjJCQq+LJzXZXtdQHiH/IcgTinUZU7wqMLb4l7VcIw5d9apMAKrwCRBsxltxs2Jj5daUmyavk3IXK68dDKTYUQ0/yCzMmO+dPb8muq+kqRUgsJ2QjZib8EtjxXCxpR6bzoVYtQyYiTIhMRVddIdKVEH2nQL7DlIhAi9tJSdeo0qhm4dZ3eqKMpmQiIRammmIiptKH6wwZ7k9WGYRoIoq4VxHYwIXEuKmDydB6c1XGdW78nRwYKYD6DStDN9QBC+dW1jnbl1gk9dXDqSKXdSwpJfv4c8x7xvMqtLeSkoKE1qXq4xwD1mbM=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
